### ISSUE TITLE
Audio duplicated in multighost races.

### ISSUE THREAD

**Issue by swampatha** [stblr/mkw-sp#103]
When watching a replay multiple ghosts at once, the sounds for all ghosts play, so if you have close times they're essentially playing at the same time. You can see that here with the water fountain sound effect and the lap count sound effect: [YouTube](https://www.youtube.com/watch?v=pIeeE_G1Qw8).

Perhaps make it so only the actively viewed ghost has audio playing?

**Comment by kierio04** [comment]
What you are suggesting is actually how it was in the base 0.1 release, and #87 was opened to make the difference between the release and how it is now a toggleable option (after reading your issue, it is now obvious that some people prefer to have audio and some don't). Hopefully that clears this up :)

**Comment by stblr** [comment]
Sadly having the selected ghost do things differently than the others is adding quite a lot of complexity, we might want to add support to live replay and encourage people to use that instead.
