### ISSUE TITLE
Input display

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#108]

**Comment by riidefi** [comment]
> [stebler] I'm looking at ctgp records and the like right now
![image](https://user-images.githubusercontent.com/34194588/152554946-7105c534-2d02-4f3d-8507-56dd24bc4eca.png)
![image](https://user-images.githubusercontent.com/34194588/152554969-c9c53f60-ccb7-4640-ba50-1ccc016c8451.png)
![image](https://user-images.githubusercontent.com/34194588/152554976-6a611a3f-6539-4859-b727-8d1fc6b4a6bf.png)
