### ISSUE TITLE
Speedometer not accurate in cannons

### ISSUE THREAD

**Issue by riidefi** [stblr/mkw-sp#126]
Drastically underreports the speed.

**Comment by kierio04** [comment]
Just curious, what velocity value is used for the speedometer? engine speed, engine+moving road speed, inaccurate memory address that stored “XYZ speed”, true XYZ speed via norm calc, or true XZ speed via norm calc?

**Comment by stblr** [comment]
With the fix, it's now:
- XYZ speed when in cannons
- engine speed with moving road and moving water speed in the direction of the engine speed otherwise
