### ISSUE TITLE
Freeze in character selection UI

### ISSUE THREAD

**Issue by riidefi** [stblr/mkw-sp#138]
Repro:
Race against exactly 3 ghosts of unique weight class (e.g. Toad, Mario, and Bowser). Mid-race, quit to the Character Selection menu. Select any character.

Crash spot: SP PAL 0x806c7bc4
Crash details: 
![image](https://user-images.githubusercontent.com/34194588/153122087-9402329c-40f3-48e3-a9e8-c4accdfc4d43.png)

We could easily add a failure condition after n tries, but perhaps there's a more fundamental issue here that should be addressed.

**Comment by stblr** [comment]
Looks like the game doesn't reset the player type of the ghost.

**Comment by stblr** [comment]
There is a fix for that 97f303837435ec01ad4eaae382c57936c7cce3b3 but it's only for replays.
