### ISSUE TITLE
Once you spectate a ghost, that is all you can do

### ISSUE THREAD

**Issue by riidefi** [stblr/mkw-sp#152]
Repro:
- Start a solo TT (works)
- Watch a ghost race
- Start a solo TT (doesn't work, starts a ghost race)

Bisection:
6ede49af9f9798b67567d266977aec2e5b57f6b2 is the first bad commit
commit 6ede49af9f9798b67567d266977aec2e5b57f6b2
Author: Pablo Stebler <pablo@stebler.xyz>
Date:   Thu Feb 10 15:20:49 2022 +0100

    Make the ghost watch pause menu more consistent
    
    Closes #131.

 assets/button/ctrl/PauseMenuGhostWatch.brctr.json5 | 76 ++++++++++++++++++----
 payload/game/ui/page/RaceMenuPage.c                |  6 +-
 2 files changed, 68 insertions(+), 14 deletions(-)

**Comment by stblr** [comment]
What buttons were used to switch between race and replay?

**Comment by riidefi** [comment]
Change course--should've specified.

**Comment by stblr** [comment]
Ok I can reproduce now.
