### ISSUE TITLE
Consider using something with a higher compression ratio than SZS

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#283]
We need to check that reading from the SD indeed takes much more time than decompressing on console (this is not the case on Dolphin because SD timings are not emulated). Aside from loading times, this would reduce the space used notably by CTs on the storage medium.

**Comment by Coffee-Toffee** [comment]
If this becomes the case, I'd appreciate if there was a convenient tool or something to convert into it (from a folder with the course stuff in it (the folder like when I do wszst extract course.szs)

**Comment by stblr** [comment]
Such a tool will be needed to do the conversion in the first place. And to be clear SZS will still be supported.

**Comment by stblr** [comment]
We are now using LZMA (SZS is still supported of course), there is `lzmac.py` and `lzmad.py` in the repo to compress and decompress respectively. Web tooling (convert.mkw-sp.com or something) is tracked in #314.
