### ISSUE TITLE
cant quit out of vs races

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#474]
![image](https://user-images.githubusercontent.com/70397032/201497761-c6c95208-e507-4f15-a2a2-d4214dd5377c.png)
clicking a here just closes the prompt but doesnt actually quit

**Comment by stblr** [comment]
https://github.com/stblr/mkw-sp/blob/0d097703ddcdcc823b28f5c7b5da1d77b04b1d1f/payload/game/ui/page/CupSelectPage.S#L40
