### ISSUE TITLE
Assigning a mii when creating a new licence doesnt work.

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#478]
When creating a new licence and choosing a mii there is a weird newline in the confirmation box 
![image](https://user-images.githubusercontent.com/70397032/201755682-fea7d70e-5d46-406b-9b82-251891bc26cd.png)

then it kicks you back here but as you can see it has the player mii on this licence now 
![image](https://user-images.githubusercontent.com/70397032/201755757-8d691fcd-fd9a-45b9-af79-4d69188175df.png)

going back into the licence settings and changing the mii again will not have the newline anymore and will work properly
![image](https://user-images.githubusercontent.com/70397032/201755907-dae83deb-b892-4ac0-afd7-3c1d0b47711a.png)

**Comment by Zachruff** [comment]
wait i think its applying the mii to the licence before it in the list, when creating my 4th licence i assigned the gunk mii to it, but it has now placed that on the 3rd licence and the 4th is stuck with player 

![image](https://user-images.githubusercontent.com/70397032/201756330-1949393d-3952-4216-9f98-a07fa3b3df4e.png)

**Comment by stblr** [comment]
The newline is here in the vanilla game (E locale).
