### ISSUE TITLE
Region line settings.

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#480]
In the vanilla game, the region line only happens online (offline its either a yellowish gold in single player mode or matches your team/player number in local vs)

the default option should be to match system settings, right now the default option is red

also need to double check that it doesnt take priority over team mode line colors.

**Comment by MikeIsAStar** [comment]
Resolved in commit [d55f44d](https://github.com/stblr/mkw-sp/pull/489/commits/d55f44d9ab33de9e9a177649ce3582e186eb2406) and [3cd9067](https://github.com/stblr/mkw-sp/pull/491/commits/3cd9067aaaac5f3ef486789bf9d25a0695df330d).
