### ISSUE TITLE
Some VS settings are missing

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#519]

**Comment by GnomedDev** [comment]
What settings?

**Comment by Gaberboo** [comment]
CPU difficulty and item frequency

**Comment by Naim2000** [comment]
And engine class

![Screenshot from 2023-02-10 16-10-08](https://user-images.githubusercontent.com/44107089/218198712-4090ee79-5958-47a7-9186-480503e8aca0.png)
![Screenshot from 2023-02-10 16-11-21](https://user-images.githubusercontent.com/44107089/218198739-22022c5d-b4a0-43d1-b982-011670d72760.png)

**Comment by GnomedDev** [comment]
> And engine class

See the 4th option

**Comment by Naim2000** [comment]
Oh that went over my head
