### ISSUE TITLE
Out of memory error when going back to select a track from TTs.

### ISSUE THREAD

**Issue by henrymkw** [stblr/mkw-sp#553]
I've gotten this to happen a decent number of times. I have only gotten the error on console however. Link bellow is the stack trace for NTSC-U.
https://cdn.discordapp.com/attachments/932048315082756187/1060368270059901008/image.png

**Comment by MikeIsAStar** [comment]
This issue seems to be a duplicate of issue #530.

**Comment by henrymkw** [comment]
Ah sorry, I’ll close then.
