### ISSUE TITLE
Add Live2D SDK and replace Miis with Anime

### ISSUE THREAD

**Issue by riidefi** [stblr/mkw-sp#631]

**Comment by vabold** [comment]
I think you would max out MEM0 from the instructions alone.

**Comment by Lami-Lemmy** [comment]
Is this really within the scope of SP?

Also Vabold I thought you had homework to finish :)

**Comment by riidefi** [comment]
I believe MEM0 is only available on WiiU? @mkwcat would know more

**Comment by mkwcat** [comment]
MEM0 is the EFB so you can use it on Wii too, I think what vabold meant is that it would max out the EFB from the instructions to the GPU

**Comment by riidefi** [comment]
Notably the Live2D Native Core SDK is not provided for PowerPC, although it is for ARM. Therefore, I believe we will need to implement Live2D Core as an IOS module for the ARM co-processor accessible to the primary PPC chip

**Comment by riidefi** [comment]
Alternatively, we could look at lifting/transpiling an ARM build to PowerPC.

**Comment by vabold** [comment]
Alternatively, you could go outside and be normal.

**Comment by mkwcat** [comment]
You can't access MEM0 from the ARM core

**Comment by vabold** [comment]
@stblr I think this issue needs the "critical" tag applied to indicate its top-priority status.
