### ISSUE TITLE
Discussion: Revert configure.py back to explicitly defining files

### ISSUE THREAD

**Issue by vabold** [stblr/mkw-sp#646]

**Comment by stblr** [comment]
Another annoying point I didn't think about initially is that the build isn't guaranteed to work anymore on a checkout. At best it will fail with an error but in some cases it could be silent.

There are valid points for using a glob but they should be covered differently (e.g. with an out of band orphan check in CI).

But overall there are good reasons why most projects don't do that.

**Comment by stblr** [comment]
Closed in #693.
