### ISSUE TITLE
Non Resetting Value: Minimap Icon Size

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#69]
From: https://tcrf.net/Bugs:Mario_Kart_Wii

"There's a bug in the game's code that causes the minimap character icons to be bigger than they are intended. When playing a normal race, the icons are the normal size, unless you've played Time Trials. When the game launches, these icons are set to a specific scale. When playing Time Trials, these icons are made larger because the only other racer is the ghost. These icons aren't scaled back down when you quit Time Trials so they remain a bigger size until the game is reset."

**Comment by stblr** [comment]
This one _might_ already be fixed.

**Comment by stblr** [comment]
This is fixed.
