### ISSUE TITLE
Feature gate online mode

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#708]

**Comment by GnomedDev** [comment]
Do you want files to be wrapped in guards to be completely removed from the build or just hide the buttons and settings?

**Comment by stblr** [comment]
Minimal changes so just hidden buttons and settings.

The plan was to generate files such as `build/features/Online.h` with just a preprocessor define. These files would be order-only dependencies of all source files. Then source files that actually use them would include them with e.g. `#include <features/Online.h>`. That way features could be enabled/disabled without requiring a full rebuild. This is also what's currently done for protobuf files.

**Comment by GnomedDev** [comment]
Those sound like two opposite systems? Why not just have a define in Registry.hh or whatever then branch on that?

**Comment by stblr** [comment]
To make it configurable with an argument in `build.py`.
