### ISSUE TITLE
Drop save states

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#710]
The implementation is a large hack that is only going to cause problems going forward. The plan is to hide it in 0.1.10 (#709) and remove it from the code base in 0.1.11.

**Comment by GnomedDev** [comment]
Could a cleaner implementation by just grabbing the useful values (stuff synced online, I guess) be accepted? Or is this just not a feature that is for SP?

**Comment by stblr** [comment]
I think that this is a great feature for SP, but that the implementation should not stay in the current state, where cryptic workarounds like #652 are needed.

**Comment by vabold** [comment]
Agreed. I think for savestates to be properly implemented, we will need to thoroughly examine a full scope and plan accordingly.
