### ISSUE TITLE
Wrong Character Icon Shadow Orientation in Live Replay

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#74]
From TCRF: https://tcrf.net/Bugs:Mario_Kart_Wii

"In online play, when watching a Live Replay, if the player switches perspectives with another racer, the shadow drop seen in its minimap icon will appear in the right hand side of it (similar to how it looks when looking at the results) instead of in the center as usual. This small bug will occur if the player switches the racer at least once, and after that, it will persist until the race is over."

**Comment by stblr** [comment]
Superseded by #76.
