### ISSUE TITLE
Have better version numbering guidelines.

### ISSUE THREAD

**Issue by Zachruff** [stblr/mkw-sp#766]
0.1.10 and 0.1.11 should not be "equal" updates lol

**Comment by GnomedDev** [comment]
0.1.10 should probably have just been a hotfix

**Comment by Zachruff** [comment]
imo first number is major new features added, second is minor new features added, third is bugfixes

**Comment by stblr** [comment]
The versioning scheme has been clearly defined since the beginning, changing it would only create confusion. I also much prefer it over any of these proposals.
